const data = [
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "湘潭市中心医院",
    "techSupportName": "chenheping",
    "doctorName": "陈和平",
    "doctorUsername": "chenheping",
    "patientIncreased": 5,
    "patientModify": 0,
    "caseIncreased": 7,
    "caseModify": 0,
    "validNewNumber": 5,
    "validFollowCase": 2,
    "medicineCase": 7,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 6,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "湘潭市中心医院",
    "techSupportName": "chenlu",
    "doctorName": "陈路",
    "doctorUsername": "chenlu",
    "patientIncreased": 10,
    "patientModify": 0,
    "caseIncreased": 13,
    "caseModify": 0,
    "validNewNumber": 10,
    "validFollowCase": 3,
    "medicineCase": 13,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 12,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "海口市第四人民医院",
    "techSupportName": "chennanyao",
    "doctorName": "陈南耀",
    "doctorUsername": "chennanyao",
    "patientIncreased": 10,
    "patientModify": 0,
    "caseIncreased": 13,
    "caseModify": 0,
    "validNewNumber": 10,
    "validFollowCase": 3,
    "medicineCase": 13,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 12,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "上海交通大学医学院附属瑞金医院",
    "techSupportName": "chenshengdi",
    "doctorName": "陈生弟",
    "doctorUsername": "chenshengdi",
    "patientIncreased": 50,
    "patientModify": 0,
    "caseIncreased": 66,
    "caseModify": 0,
    "validNewNumber": 50,
    "validFollowCase": 16,
    "medicineCase": 66,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 64,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "安徽医科大学第一附属医院",
    "techSupportName": "chenxianwen",
    "doctorName": "陈先文",
    "doctorUsername": "chenxianwen",
    "patientIncreased": 1,
    "patientModify": 0,
    "caseIncreased": 1,
    "caseModify": 0,
    "validNewNumber": 1,
    "validFollowCase": 0,
    "medicineCase": 1,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 1,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "西安市第九医院",
    "techSupportName": "chenyi",
    "doctorName": "陈艺",
    "doctorUsername": "chenyi",
    "patientIncreased": 50,
    "patientModify": 0,
    "caseIncreased": 64,
    "caseModify": 0,
    "validNewNumber": 50,
    "validFollowCase": 14,
    "medicineCase": 64,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 61,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "湘潭市中心医院",
    "techSupportName": "chenzhi",
    "doctorName": "陈知",
    "doctorUsername": "chenzhi",
    "patientIncreased": 3,
    "patientModify": 0,
    "caseIncreased": 5,
    "caseModify": 0,
    "validNewNumber": 3,
    "validFollowCase": 2,
    "medicineCase": 5,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 4,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "湘潭市中心医院",
    "techSupportName": "daizhicheng",
    "doctorName": "戴至诚",
    "doctorUsername": "daizhicheng",
    "patientIncreased": 30,
    "patientModify": 0,
    "caseIncreased": 41,
    "caseModify": 0,
    "validNewNumber": 30,
    "validFollowCase": 11,
    "medicineCase": 41,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 36,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "西安交通大学第二附属医院",
    "techSupportName": "dengying",
    "doctorName": "邓颖",
    "doctorUsername": "dengying",
    "patientIncreased": 50,
    "patientModify": 0,
    "caseIncreased": 73,
    "caseModify": 0,
    "validNewNumber": 50,
    "validFollowCase": 23,
    "medicineCase": 73,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 66,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "西安市中心医院",
    "techSupportName": "dizhengli",
    "doctorName": "狄政莉",
    "doctorUsername": "dizhengli",
    "patientIncreased": 3,
    "patientModify": 0,
    "caseIncreased": 5,
    "caseModify": 0,
    "validNewNumber": 3,
    "validFollowCase": 2,
    "medicineCase": 5,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 4,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "海口市第三人民医院",
    "techSupportName": "fengqingchun",
    "doctorName": "冯青春",
    "doctorUsername": "fengqingchun",
    "patientIncreased": 4,
    "patientModify": 0,
    "caseIncreased": 6,
    "caseModify": 0,
    "validNewNumber": 4,
    "validFollowCase": 2,
    "medicineCase": 6,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 4,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "文昌市人民医院",
    "techSupportName": "fuyuecai",
    "doctorName": "符悦才",
    "doctorUsername": "fuyuecai",
    "patientIncreased": 4,
    "patientModify": 0,
    "caseIncreased": 5,
    "caseModify": 0,
    "validNewNumber": 4,
    "validFollowCase": 1,
    "medicineCase": 5,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 5,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "上海市同济医院",
    "techSupportName": "guanqiang",
    "doctorName": "管强",
    "doctorUsername": "guanqiang",
    "patientIncreased": 10,
    "patientModify": 0,
    "caseIncreased": 12,
    "caseModify": 0,
    "validNewNumber": 10,
    "validFollowCase": 2,
    "medicineCase": 12,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 12,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "广西壮族自治区人民医院",
    "techSupportName": "hanmin",
    "doctorName": "韩敏",
    "doctorUsername": "hanmin",
    "patientIncreased": 50,
    "patientModify": 0,
    "caseIncreased": 64,
    "caseModify": 0,
    "validNewNumber": 50,
    "validFollowCase": 14,
    "medicineCase": 64,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 62,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "中南大学湘雅二医院",
    "techSupportName": "houying",
    "doctorName": "后颖",
    "doctorUsername": "houying",
    "patientIncreased": 10,
    "patientModify": 0,
    "caseIncreased": 13,
    "caseModify": 0,
    "validNewNumber": 10,
    "validFollowCase": 3,
    "medicineCase": 13,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 12,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "海南省人民医院",
    "techSupportName": "huangdan",
    "doctorName": "黄丹",
    "doctorUsername": "huangdan",
    "patientIncreased": 3,
    "patientModify": 0,
    "caseIncreased": 5,
    "caseModify": 0,
    "validNewNumber": 3,
    "validFollowCase": 2,
    "medicineCase": 5,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 5,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "陆军军医大学附属第一医院",
    "techSupportName": "huangheqing",
    "doctorName": "黄河清",
    "doctorUsername": "huangheqing",
    "patientIncreased": 10,
    "patientModify": 0,
    "caseIncreased": 13,
    "caseModify": 0,
    "validNewNumber": 10,
    "validFollowCase": 3,
    "medicineCase": 13,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 13,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "海南省中医院",
    "techSupportName": "huanghongmin",
    "doctorName": "黄宏敏",
    "doctorUsername": "huanghongmin",
    "patientIncreased": 10,
    "patientModify": 0,
    "caseIncreased": 17,
    "caseModify": 0,
    "validNewNumber": 10,
    "validFollowCase": 7,
    "medicineCase": 17,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 16,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "首都医科大学附属北京康复医院",
    "techSupportName": "huangpeiling",
    "doctorName": "黄佩玲",
    "doctorUsername": "huangpeiling",
    "patientIncreased": 1,
    "patientModify": 0,
    "caseIncreased": 2,
    "caseModify": 0,
    "validNewNumber": 1,
    "validFollowCase": 1,
    "medicineCase": 2,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 2,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "武汉市第五医院",
    "techSupportName": "hurenlin",
    "doctorName": "胡仁琳",
    "doctorUsername": "hurenlin",
    "patientIncreased": 10,
    "patientModify": 0,
    "caseIncreased": 15,
    "caseModify": 0,
    "validNewNumber": 10,
    "validFollowCase": 5,
    "medicineCase": 15,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 14,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "苏州大学附属第二医院",
    "techSupportName": "jinhong",
    "doctorName": "金宏",
    "doctorUsername": "jinhong",
    "patientIncreased": 30,
    "patientModify": 0,
    "caseIncreased": 36,
    "caseModify": 0,
    "validNewNumber": 30,
    "validFollowCase": 6,
    "medicineCase": 36,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 36,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "习水县人民医院",
    "techSupportName": "laiqiande",
    "doctorName": "赖乾德",
    "doctorUsername": "laiqiande",
    "patientIncreased": 9,
    "patientModify": 0,
    "caseIncreased": 11,
    "caseModify": 0,
    "validNewNumber": 9,
    "validFollowCase": 2,
    "medicineCase": 11,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 11,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "南昌大学第一附属医院",
    "techSupportName": "limenghua",
    "doctorName": "李梦华",
    "doctorUsername": "limenghua",
    "patientIncreased": 10,
    "patientModify": 0,
    "caseIncreased": 15,
    "caseModify": 0,
    "validNewNumber": 10,
    "validFollowCase": 5,
    "medicineCase": 15,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 14,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "海南省农垦三亚医院",
    "techSupportName": "linkang",
    "doctorName": "林康",
    "doctorUsername": "linkang",
    "patientIncreased": 10,
    "patientModify": 0,
    "caseIncreased": 15,
    "caseModify": 0,
    "validNewNumber": 10,
    "validFollowCase": 5,
    "medicineCase": 15,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 14,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "湖北新华医院",
    "techSupportName": "liping",
    "doctorName": "李平",
    "doctorUsername": "liping",
    "patientIncreased": 10,
    "patientModify": 0,
    "caseIncreased": 12,
    "caseModify": 0,
    "validNewNumber": 10,
    "validFollowCase": 2,
    "medicineCase": 12,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 11,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "上海交通大学医学院附属瑞金医院",
    "techSupportName": "liujun",
    "doctorName": "刘军",
    "doctorUsername": "liujun",
    "patientIncreased": 30,
    "patientModify": 0,
    "caseIncreased": 40,
    "caseModify": 0,
    "validNewNumber": 30,
    "validFollowCase": 10,
    "medicineCase": 40,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 38,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "南京脑科医院",
    "techSupportName": "liuweiguo",
    "doctorName": "刘卫国",
    "doctorUsername": "liuweiguo",
    "patientIncreased": 50,
    "patientModify": 0,
    "caseIncreased": 68,
    "caseModify": 0,
    "validNewNumber": 50,
    "validFollowCase": 18,
    "medicineCase": 68,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 67,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "西安市中心医院",
    "techSupportName": "liuweiqiang",
    "doctorName": "刘卫强",
    "doctorUsername": "liuweiqiang",
    "patientIncreased": 30,
    "patientModify": 0,
    "caseIncreased": 36,
    "caseModify": 0,
    "validNewNumber": 30,
    "validFollowCase": 6,
    "medicineCase": 36,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 35,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "空军军医大学西京医院",
    "techSupportName": "liuxuedong",
    "doctorName": "刘学东",
    "doctorUsername": "liuxuedong",
    "patientIncreased": 30,
    "patientModify": 0,
    "caseIncreased": 43,
    "caseModify": 0,
    "validNewNumber": 30,
    "validFollowCase": 13,
    "medicineCase": 43,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 40,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "湘潭市第一人民医院",
    "techSupportName": "liwanqian",
    "doctorName": "李宛褰",
    "doctorUsername": "liwanqian",
    "patientIncreased": 10,
    "patientModify": 0,
    "caseIncreased": 13,
    "caseModify": 0,
    "validNewNumber": 10,
    "validFollowCase": 3,
    "medicineCase": 13,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 13,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "湘潭市中心医院",
    "techSupportName": "liwen",
    "doctorName": "李文",
    "doctorUsername": "liwen",
    "patientIncreased": 30,
    "patientModify": 0,
    "caseIncreased": 45,
    "caseModify": 0,
    "validNewNumber": 30,
    "validFollowCase": 15,
    "medicineCase": 45,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 44,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "河南省人民医院",
    "techSupportName": "lixue",
    "doctorName": "李学",
    "doctorUsername": "lixue",
    "patientIncreased": 10,
    "patientModify": 0,
    "caseIncreased": 14,
    "caseModify": 0,
    "validNewNumber": 10,
    "validFollowCase": 4,
    "medicineCase": 14,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 14,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "海南省农垦总医院",
    "techSupportName": "longfaqing",
    "doctorName": "龙发青",
    "doctorUsername": "longfaqing",
    "patientIncreased": 10,
    "patientModify": 0,
    "caseIncreased": 15,
    "caseModify": 0,
    "validNewNumber": 10,
    "validFollowCase": 5,
    "medicineCase": 15,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 14,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "四川省人民医院",
    "techSupportName": "luoyongjie",
    "doctorName": "罗永杰",
    "doctorUsername": "luoyongjie",
    "patientIncreased": 10,
    "patientModify": 0,
    "caseIncreased": 15,
    "caseModify": 0,
    "validNewNumber": 10,
    "validFollowCase": 5,
    "medicineCase": 15,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 14,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "浙江大学医学院附属邵逸夫医院",
    "techSupportName": "lvwen",
    "doctorName": "吕文",
    "doctorUsername": "lvwen",
    "patientIncreased": 30,
    "patientModify": 0,
    "caseIncreased": 46,
    "caseModify": 0,
    "validNewNumber": 30,
    "validFollowCase": 16,
    "medicineCase": 46,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 42,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "湘潭市第一人民医院",
    "techSupportName": "moxiaoyu",
    "doctorName": "莫晓宇",
    "doctorUsername": "moxiaoyu",
    "patientIncreased": 10,
    "patientModify": 0,
    "caseIncreased": 14,
    "caseModify": 0,
    "validNewNumber": 10,
    "validFollowCase": 4,
    "medicineCase": 14,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 13,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "韶山市人民医院",
    "techSupportName": "penglong",
    "doctorName": "彭龙",
    "doctorUsername": "penglong",
    "patientIncreased": 30,
    "patientModify": 0,
    "caseIncreased": 41,
    "caseModify": 0,
    "validNewNumber": 30,
    "validFollowCase": 11,
    "medicineCase": 41,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 39,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "成都市第三人民医院",
    "techSupportName": "shenfuwei",
    "doctorName": "沈富伟",
    "doctorUsername": "shenfuwei",
    "patientIncreased": 9,
    "patientModify": 0,
    "caseIncreased": 12,
    "caseModify": 0,
    "validNewNumber": 9,
    "validFollowCase": 3,
    "medicineCase": 12,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 12,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "广西医科大学第一附属医院",
    "techSupportName": "shenyuefei",
    "doctorName": "沈岳飞",
    "doctorUsername": "shenyuefei",
    "patientIncreased": 50,
    "patientModify": 0,
    "caseIncreased": 70,
    "caseModify": 0,
    "validNewNumber": 50,
    "validFollowCase": 20,
    "medicineCase": 70,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 67,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "北京大学第一医院",
    "techSupportName": "sunwei",
    "doctorName": "孙葳",
    "doctorUsername": "sunwei",
    "patientIncreased": 10,
    "patientModify": 0,
    "caseIncreased": 13,
    "caseModify": 0,
    "validNewNumber": 10,
    "validFollowCase": 3,
    "medicineCase": 13,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 13,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "湘潭市第一人民医院",
    "techSupportName": "tangling",
    "doctorName": "汤陵",
    "doctorUsername": "tangling",
    "patientIncreased": 10,
    "patientModify": 0,
    "caseIncreased": 12,
    "caseModify": 0,
    "validNewNumber": 10,
    "validFollowCase": 2,
    "medicineCase": 12,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 12,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "广州医科大学附属第一医院",
    "techSupportName": "tanhongyu",
    "doctorName": "谭红愉",
    "doctorUsername": "tanhongyu",
    "patientIncreased": 30,
    "patientModify": 0,
    "caseIncreased": 44,
    "caseModify": 0,
    "validNewNumber": 30,
    "validFollowCase": 14,
    "medicineCase": 44,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 41,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "空军军医大学唐都医院",
    "techSupportName": "tddbs",
    "doctorName": "surgeon",
    "doctorUsername": "tddbs",
    "patientIncreased": 30,
    "patientModify": 0,
    "caseIncreased": 39,
    "caseModify": 0,
    "validNewNumber": 30,
    "validFollowCase": 9,
    "medicineCase": 39,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 38,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "贵阳市中西医结合医院（贵阳市第六人民医院）",
    "techSupportName": "tianshimin",
    "doctorName": "田时敏",
    "doctorUsername": "tianshimin",
    "patientIncreased": 7,
    "patientModify": 0,
    "caseIncreased": 9,
    "caseModify": 0,
    "validNewNumber": 7,
    "validFollowCase": 2,
    "medicineCase": 9,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 8,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "西安市中医医院",
    "techSupportName": "wangfei",
    "doctorName": "王飞",
    "doctorUsername": "wangfei",
    "patientIncreased": 50,
    "patientModify": 0,
    "caseIncreased": 69,
    "caseModify": 0,
    "validNewNumber": 50,
    "validFollowCase": 19,
    "medicineCase": 69,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 65,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "南方医科大学南方医院",
    "techSupportName": "wangqun",
    "doctorName": "王群",
    "doctorUsername": "wangqun",
    "patientIncreased": 30,
    "patientModify": 0,
    "caseIncreased": 41,
    "caseModify": 0,
    "validNewNumber": 30,
    "validFollowCase": 11,
    "medicineCase": 41,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 39,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "广东省人民医院",
    "techSupportName": "wangwanyi",
    "doctorName": "王婉怡",
    "doctorUsername": "wangwanyi",
    "patientIncreased": 2,
    "patientModify": 0,
    "caseIncreased": 3,
    "caseModify": 0,
    "validNewNumber": 2,
    "validFollowCase": 1,
    "medicineCase": 3,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 3,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "山西省人民医院",
    "techSupportName": "wuqing",
    "doctorName": "吴琴",
    "doctorUsername": "wuqing",
    "patientIncreased": 10,
    "patientModify": 0,
    "caseIncreased": 15,
    "caseModify": 0,
    "validNewNumber": 10,
    "validFollowCase": 5,
    "medicineCase": 15,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 14,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "万宁市人民医院",
    "techSupportName": "wuzehai",
    "doctorName": "吴泽海",
    "doctorUsername": "wuzehai",
    "patientIncreased": 7,
    "patientModify": 0,
    "caseIncreased": 8,
    "caseModify": 0,
    "validNewNumber": 7,
    "validFollowCase": 1,
    "medicineCase": 8,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 8,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "广州医科大学附属第一医院",
    "techSupportName": "wuzhuohua",
    "doctorName": "吴卓华",
    "doctorUsername": "wuzhuohua",
    "patientIncreased": 30,
    "patientModify": 0,
    "caseIncreased": 42,
    "caseModify": 0,
    "validNewNumber": 30,
    "validFollowCase": 12,
    "medicineCase": 42,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 40,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "兰州大学第二医院",
    "techSupportName": "xianguitao",
    "doctorName": "鲜桂涛",
    "doctorUsername": "xianguitao",
    "patientIncreased": 50,
    "patientModify": 0,
    "caseIncreased": 71,
    "caseModify": 0,
    "validNewNumber": 50,
    "validFollowCase": 21,
    "medicineCase": 71,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 69,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "温州医科大学附属第一医院",
    "techSupportName": "xiechenglong",
    "doctorName": "谢成龙",
    "doctorUsername": "xiechenglong",
    "patientIncreased": 9,
    "patientModify": 0,
    "caseIncreased": 10,
    "caseModify": 0,
    "validNewNumber": 9,
    "validFollowCase": 1,
    "medicineCase": 10,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 10,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "湘潭市第二人民医院",
    "techSupportName": "xietianle",
    "doctorName": "谢添乐",
    "doctorUsername": "xietianle",
    "patientIncreased": 5,
    "patientModify": 0,
    "caseIncreased": 8,
    "caseModify": 0,
    "validNewNumber": 5,
    "validFollowCase": 3,
    "medicineCase": 8,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 7,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "广州医科大学附属第一医院",
    "techSupportName": "xupingyi",
    "doctorName": "徐评议",
    "doctorUsername": "xupingyi",
    "patientIncreased": 30,
    "patientModify": 0,
    "caseIncreased": 47,
    "caseModify": 0,
    "validNewNumber": 30,
    "validFollowCase": 17,
    "medicineCase": 47,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 44,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "山西医科大学附属第一医院",
    "techSupportName": "yanghuilin",
    "doctorName": "杨慧琳",
    "doctorUsername": "yanghuilin",
    "patientIncreased": 50,
    "patientModify": 0,
    "caseIncreased": 69,
    "caseModify": 0,
    "validNewNumber": 50,
    "validFollowCase": 19,
    "medicineCase": 69,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 60,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "海南医学院附属医院",
    "techSupportName": "yangxin",
    "doctorName": "杨欣",
    "doctorUsername": "yangxin",
    "patientIncreased": 30,
    "patientModify": 0,
    "caseIncreased": 46,
    "caseModify": 0,
    "validNewNumber": 30,
    "validFollowCase": 16,
    "medicineCase": 46,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 42,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "大连医科大学附属第一医院",
    "techSupportName": "yinxiaoxue",
    "doctorName": "殷肖雪",
    "doctorUsername": "yinxiaoxue",
    "patientIncreased": 1,
    "patientModify": 0,
    "caseIncreased": 2,
    "caseModify": 0,
    "validNewNumber": 1,
    "validFollowCase": 1,
    "medicineCase": 2,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 2,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "韶山市人民医院",
    "techSupportName": "yuanxing",
    "doctorName": "袁星",
    "doctorUsername": "yuanxing",
    "patientIncreased": 10,
    "patientModify": 0,
    "caseIncreased": 15,
    "caseModify": 0,
    "validNewNumber": 10,
    "validFollowCase": 5,
    "medicineCase": 15,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 15,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "深圳市第二人民医院",
    "techSupportName": "zhangdoudou",
    "doctorName": "张豆豆",
    "doctorUsername": "zhangdoudou",
    "patientIncreased": 5,
    "patientModify": 0,
    "caseIncreased": 7,
    "caseModify": 0,
    "validNewNumber": 5,
    "validFollowCase": 2,
    "medicineCase": 7,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 5,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "湘潭市中心医院",
    "techSupportName": "zhangtingting",
    "doctorName": "张婷婷",
    "doctorUsername": "zhangtingting",
    "patientIncreased": 2,
    "patientModify": 0,
    "caseIncreased": 2,
    "caseModify": 0,
    "validNewNumber": 2,
    "validFollowCase": 0,
    "medicineCase": 2,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 2,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "陕西省人民医院",
    "techSupportName": "zhangwenhai",
    "doctorName": "张文海",
    "doctorUsername": "zhangwenhai",
    "patientIncreased": 50,
    "patientModify": 0,
    "caseIncreased": 67,
    "caseModify": 0,
    "validNewNumber": 50,
    "validFollowCase": 17,
    "medicineCase": 67,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 65,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "西安交通大学第二附属医院",
    "techSupportName": "zhanshuqin",
    "doctorName": "展淑琴",
    "doctorUsername": "zhanshuqin",
    "patientIncreased": 1,
    "patientModify": 0,
    "caseIncreased": 1,
    "caseModify": 0,
    "validNewNumber": 1,
    "validFollowCase": 0,
    "medicineCase": 1,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 1,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "首都医科大学宣武医院",
    "techSupportName": "zhanshuqin01",
    "doctorName": "詹淑琴",
    "doctorUsername": "zhanshuqin01",
    "patientIncreased": 30,
    "patientModify": 0,
    "caseIncreased": 41,
    "caseModify": 0,
    "validNewNumber": 30,
    "validFollowCase": 11,
    "medicineCase": 41,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 40,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "湘潭市中心医院",
    "techSupportName": "zhaodijian",
    "doctorName": "赵迪坚",
    "doctorUsername": "zhaodijian",
    "patientIncreased": 30,
    "patientModify": 0,
    "caseIncreased": 38,
    "caseModify": 0,
    "validNewNumber": 30,
    "validFollowCase": 8,
    "medicineCase": 38,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 34,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "三亚市中医院",
    "techSupportName": "zhengyongliang",
    "doctorName": "郑永亮",
    "doctorUsername": "zhengyongliang",
    "patientIncreased": 30,
    "patientModify": 0,
    "caseIncreased": 43,
    "caseModify": 0,
    "validNewNumber": 30,
    "validFollowCase": 13,
    "medicineCase": 43,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 41,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "三亚市人民医院",
    "techSupportName": "zhouhui",
    "doctorName": "周辉",
    "doctorUsername": "zhouhui",
    "patientIncreased": 30,
    "patientModify": 0,
    "caseIncreased": 44,
    "caseModify": 0,
    "validNewNumber": 30,
    "validFollowCase": 14,
    "medicineCase": 44,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 39,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "湘潭市中心医院",
    "techSupportName": "zhouyou",
    "doctorName": "周游",
    "doctorUsername": "zhouyou",
    "patientIncreased": 5,
    "patientModify": 0,
    "caseIncreased": 7,
    "caseModify": 0,
    "validNewNumber": 5,
    "validFollowCase": 2,
    "medicineCase": 7,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 7,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  },
  {
    "recordTime": "2019-04-01/2019-04-30",
    "hospitalName": "毕节市人民医院",
    "techSupportName": "zhubin",
    "doctorName": "朱斌",
    "doctorUsername": "zhubin",
    "patientIncreased": 6,
    "patientModify": 0,
    "caseIncreased": 8,
    "caseModify": 0,
    "validNewNumber": 6,
    "validFollowCase": 2,
    "medicineCase": 8,
    "medicineEffectCase": 0,
    "surgeryTreat": 0,
    "physicalTreat": 0,
    "scale": 6,
    "vitalSigns": 0,
    "nerousSystem": 0,
    "bioExam": 0,
    "electroExam": 0,
    "videoInfo": 0,
    "otherMedicine": 0,
    "pastMedicalHistory": 0,
    "family": 0,
    "habit": 0,
    "cideexposed": 0
  }
];

function filterCommonHospitals(data) {
  if (!data || !data.length) {
    return [];
  }
  const oldArr = JSON.parse(JSON.stringify(data));
  let hospitals = oldArr.map((item) => {
    return item.hospitalName;
  });
  let newHospitals = [];
  let newArr = [];
  hospitals.forEach((item, index) => {
    let tempObj ={
      name: item,
      val: [],
    };
    if (newHospitals.indexOf(item) > -1) {
      var temp = newArr.find(function(sitem) {
        return sitem.name === item
      });
      temp.val.push(oldArr[index])
    } else {
      tempObj.val.push(oldArr[index]);
      newArr.push(tempObj);
      newHospitals.push(item);
    }
  });
  getTotalNum(newArr);
  let filterHospitalArr = filterSpecialHospital(newArr);
  // console.log('filterHosptialArr---', filterHosptialArr);
  let newData = [];
  filterHospitalArr.forEach((item) => {
    newData.push(sumObj(item.val))
  });
  return newData;
}
function sumObj(arr) {
  const keys = Object.keys(arr[0]);
  let tempObj = { recordTime: '',
    hospitalName: '',
    techSupportName: '',
    doctorName: '',
    doctorUsername: '',
    patientIncreased: 0,
    patientModify: 0,
    caseIncreased: 0,
    caseModify: 0,
    validNewNumber: 0,
    validFollowCase: 0,
    medicineCase: 0,
    medicineEffectCase: 0,
    surgeryTreat: 0,
    physicalTreat: 0,
    scale: 0,
    vitalSigns: 0,
    nerousSystem: 0,
    bioExam: 0,
    electroExam: 0,
    videoInfo: 0,
    otherMedicine: 0,
    pastMedicalHistory: 0,
    family: 0,
    habit: 0,
    cideexposed: 0 };
  arr.forEach((item) => {
    keys.forEach((subItem) => {
      if (typeof item[subItem] === 'number') {
        tempObj[subItem] += item[subItem];
      } else {
        tempObj[subItem] = item[subItem]
      }
    })
  });
  return tempObj;
}

function filterSpecialHospital(data) {
  const filterHospitals = ['习水县人民医院','惠州市第三人民医院'];
  const oldArr = JSON.parse(JSON.stringify(data));
  let newArr;// 过滤后的数组
  newArr = oldArr.filter((item) => {
   return filterHospitals.indexOf(item.name) === -1
  });
  return newArr;
}

function getTotalNum(data) {
  const oldArr = JSON.parse(JSON.stringify(data));
  let newData = [];
  oldArr.forEach((item) => {
    newData.push(sumObj(item.val))
  });
  const temp = sumObj(newData);
  const totalTableKey = ['patientModify', 'caseModify','validNewNumber','validFollowCase'];
  const totalTable = [];
  totalTable.push(oldArr.length);
  for (let i in temp) {
    if (typeof temp[i] === 'number' && totalTableKey.indexOf(i) === -1) {
      totalTable.push(temp[i]);
    }
  }
  return totalTable;
}

filterCommonHospitals(data);


